%{
1) Run DataPrep_Borden.m.
2) Run ToyModelAtBorden.m with HM_in_CLM set to 'yes'.
3) Change LW_in_bc_CLM_comb to LW_in_bc_CLM_HM_comb, LW_in_bc_CLM to 
   LW_in_bc_CLM_HM and T_veg_CLM to T_veg_CLM_HM, and save both in 
   CLM_Borden_HM.mat.
   LW_in_bc_CLM_HM_comb = LW_in_bc_CLM_comb;
   LW_in_bc_CLM_HM = LW_in_bc_CLM;
   T_veg_CLM_HM = T_veg_CLM;
   save('CLM_Borden_HM.mat','LW_in_bc_CLM_HM_comb','LW_in_bc_CLM_HM','T_veg_CLM_HM')
4) Run ToyModelAtBorden.m again with HM_in_CLM set to 'no'.
%}
load CLM_Borden_HM.mat

%-------------------------------------------------------------------------%
%----------------------  select evaluation periods  ----------------------%
%{
Simulation starts on 1 January 2013 11:00, so evaluation periods start on 2
January at 1:00. Meltout estimated via surface albedo happens at 18:00 on 4 
April, so evaluation period ends at 0:00 on 4 April.
%}
EP_start = 25;
EP_end = 2232;

%{
Gaps in radiometer data.
%}
gap_LW_1 = 649:696;     % 28 Jan 1:00 to 30 Jan 0:00
gap_LW_2 = 985:1008;    % 11 Feb 1:00 to 12 Feb 0:00
gap_LW_3 = 1057:1080;   % 14 Feb 1:00 to 15 Feb 0:00
gap_LW_4 = 1273:1296;   % 23 Feb 1:00 to 24 Feb 0:00
% gap_LW_5 = 1345:1392;   % 26 Feb 1:00 to 28 Feb 0:00 - included in snow
% gap_LW_6 = 1369:1416;   % 31 Mar 1:00 to 1 Mar 0:00
gap_LW_7 = 1585:1608;   % 8 Mar 1:00 to 9 Mar 0:00
gap_LW_8 = 2425:2448;   % 12 Apr 1:00 to 13 Apr 0:00

%{
Suspicious values of constant LWR around 314.3 W m^{-2}, indicating snow 
cover on radiometers, set to nan. Complete days around those timesteps are
excluded.
We extend gap #1 to include both LW gaps #5 and #6.
%}
% gap_snow_1 = 1321:1392;   % 25 Feb 1:00 to 28 Feb 0:00
gap_snow_1 = 1321:1416;   % 25 Feb 1:00 to 28 Feb 0:00
gap_snow_2 = 1969:1992;   % 24 Mar 1:00 to 25 Mar 0:00
gap_snow_3 = 2137:2160;   % 31 Mar 1:00 to 1 Apr 0:00

%{
Gap in meteorological forcing from 0:00 to 9:00 on 1 February, which,
unfortunately, means we have to exclude both 31 January and 1 February.
%}
gap_met = 721:768;

LW_sub_val_eval = horzcat(LW_in_bc_1h(EP_start:gap_LW_1(1)-1),...
    LW_in_bc_1h(gap_LW_1(end)+1:gap_met(1)-1),...
    LW_in_bc_1h(gap_met(end)+1:gap_LW_2(1)-1),...
    LW_in_bc_1h(gap_LW_2(end)+1:gap_LW_3(1)-1),...
    LW_in_bc_1h(gap_LW_3(end)+1:gap_LW_4(1)-1),...
    LW_in_bc_1h(gap_LW_4(end)+1:gap_snow_1(1)-1),...
    LW_in_bc_1h(gap_snow_1(end)+1:gap_LW_7(1)-1),...
    LW_in_bc_1h(gap_LW_7(end)+1:gap_snow_2(1)-1),...
    LW_in_bc_1h(gap_snow_2(end)+1:gap_snow_3(1)-1),...
    LW_in_bc_1h(gap_snow_3(end)+1:gap_LW_8(1)-1),...
    LW_in_bc_1h(gap_LW_8(end)+1:EP_end));
LW_sub_CLM_comb_eval = horzcat(LW_in_bc_CLM_comb(EP_start:gap_LW_1(1)-1),...
    LW_in_bc_CLM_comb(gap_LW_1(end)+1:gap_met(1)-1),...
    LW_in_bc_CLM_comb(gap_met(end)+1:gap_LW_2(1)-1),...
    LW_in_bc_CLM_comb(gap_LW_2(end)+1:gap_LW_3(1)-1),...
    LW_in_bc_CLM_comb(gap_LW_3(end)+1:gap_LW_4(1)-1),...
    LW_in_bc_CLM_comb(gap_LW_4(end)+1:gap_snow_1(1)-1),...
    LW_in_bc_CLM_comb(gap_snow_1(end)+1:gap_LW_7(1)-1),...
    LW_in_bc_CLM_comb(gap_LW_7(end)+1:gap_snow_2(1)-1),...
    LW_in_bc_CLM_comb(gap_snow_2(end)+1:gap_snow_3(1)-1),...
    LW_in_bc_CLM_comb(gap_snow_3(end)+1:gap_LW_8(1)-1),...
    LW_in_bc_CLM_comb(gap_LW_8(end)+1:EP_end));
LW_sub_CLM_eval = vertcat(LW_in_bc_CLM(EP_start:gap_LW_1(1)-1,:),...
    LW_in_bc_CLM(gap_LW_1(end)+1:gap_met(1)-1,:),...
    LW_in_bc_CLM(gap_met(end)+1:gap_LW_2(1)-1,:),...
    LW_in_bc_CLM(gap_LW_2(end)+1:gap_LW_3(1)-1,:),...
    LW_in_bc_CLM(gap_LW_3(end)+1:gap_LW_4(1)-1,:),...
    LW_in_bc_CLM(gap_LW_4(end)+1:gap_snow_1(1)-1,:),...
    LW_in_bc_CLM(gap_snow_1(end)+1:gap_LW_7(1)-1,:),...
    LW_in_bc_CLM(gap_LW_7(end)+1:gap_snow_2(1)-1,:),...
    LW_in_bc_CLM(gap_snow_2(end)+1:gap_snow_3(1)-1,:),...
    LW_in_bc_CLM(gap_snow_3(end)+1:gap_LW_8(1)-1,:),...
    LW_in_bc_CLM(gap_LW_8(end)+1:EP_end,:));
LW_sub_CLMHM_comb_eval = horzcat(LW_in_bc_CLM_HM_comb(EP_start:gap_LW_1(1)-1),...
    LW_in_bc_CLM_HM_comb(gap_LW_1(end)+1:gap_met(1)-1),...
    LW_in_bc_CLM_HM_comb(gap_met(end)+1:gap_LW_2(1)-1),...
    LW_in_bc_CLM_HM_comb(gap_LW_2(end)+1:gap_LW_3(1)-1),...
    LW_in_bc_CLM_HM_comb(gap_LW_3(end)+1:gap_LW_4(1)-1),...
    LW_in_bc_CLM_HM_comb(gap_LW_4(end)+1:gap_snow_1(1)-1),...
    LW_in_bc_CLM_HM_comb(gap_snow_1(end)+1:gap_LW_7(1)-1),...
    LW_in_bc_CLM_HM_comb(gap_LW_7(end)+1:gap_snow_2(1)-1),...
    LW_in_bc_CLM_HM_comb(gap_snow_2(end)+1:gap_snow_3(1)-1),...
    LW_in_bc_CLM_HM_comb(gap_snow_3(end)+1:gap_LW_8(1)-1),...
    LW_in_bc_CLM_HM_comb(gap_LW_8(end)+1:EP_end));
LW_sub_CLMHM_eval = vertcat(LW_in_bc_CLM_HM(EP_start:gap_LW_1(1)-1,:),...
    LW_in_bc_CLM_HM(gap_LW_1(end)+1:gap_met(1)-1,:),...
    LW_in_bc_CLM_HM(gap_met(end)+1:gap_LW_2(1)-1,:),...
    LW_in_bc_CLM_HM(gap_LW_2(end)+1:gap_LW_3(1)-1,:),...
    LW_in_bc_CLM_HM(gap_LW_3(end)+1:gap_LW_4(1)-1,:),...
    LW_in_bc_CLM_HM(gap_LW_4(end)+1:gap_snow_1(1)-1,:),...
    LW_in_bc_CLM_HM(gap_snow_1(end)+1:gap_LW_7(1)-1,:),...
    LW_in_bc_CLM_HM(gap_LW_7(end)+1:gap_snow_2(1)-1,:),...
    LW_in_bc_CLM_HM(gap_snow_2(end)+1:gap_snow_3(1)-1,:),...
    LW_in_bc_CLM_HM(gap_snow_3(end)+1:gap_LW_8(1)-1,:),...
    LW_in_bc_CLM_HM(gap_LW_8(end)+1:EP_end,:));
LW_sub_SP_eval = nan(size(LW_sub_val_eval));


%-------------------------------------------------------------------------%
%---------------------  analyse: figures, RMSE, MBD  ---------------------%
% calculate RMSE and MBD
RMSE_Borden_CLM = RMSE(length(LW_sub_val_eval),LW_sub_CLM_comb_eval,...
    LW_sub_val_eval);
RMSE_Borden_CLMHM = RMSE(length(LW_sub_val_eval),LW_sub_CLMHM_comb_eval,...
    LW_sub_val_eval);
MBD_Borden_CLM = MBD(length(LW_sub_val_eval),LW_sub_CLM_comb_eval,...
    LW_sub_val_eval);
MBD_Borden_CLMHM = MBD(length(LW_sub_val_eval),LW_sub_CLMHM_comb_eval,...
    LW_sub_val_eval);
